import { GENERATED_CODE_PLACEHOLDER, PLAN_PLACEHOLDER, TASK_PLACEHOLDER } from "@/constants";
import { CodebaseAssistant } from "@/modules/ai/assistants/CodebaseAssistant";
import { ResponseParser } from "@/modules/ai/support/ResponseParser";
import { PromptBuilder } from "@/modules/ai/support/PromptBuilder";
import { TokenLimiter } from "@/modules/ai/support/TokenLimiter";
import { LLM_MODELS } from "@/modules/utils/llmInfo";

export class WriterAssistant extends CodebaseAssistant<PRBody> {
    responseType = "xml";

    // override model to a smaller one
    overrideModel = LLM_MODELS.AWS_BEDROCK_CLAUDE_35_HAIKU_V2.id;

    constructor() {
        super(new PromptBuilder(), new TokenLimiter());
    }

    getSystemPrompt(): string {
        return `
You are a senior software engineer working on a project.
Your task is to write a clear and concise pull request (PR) description in markdown format, based on the provided task_description, implementation_plan, and generated_code.

<objective>
Analyze the task, the implementation plan, and the newly generated code to craft a comprehensive PR description. This description should provide context, outline the changes made, and explain the reasoning behind the implementation.
</objective>

<instructions>
Each PR description should include:
- Title: A brief and descriptive title for the PR.
- Summary: A concise overview of the changes and the purpose of the PR.
- Details: A detailed explanation of what was changed, why it was changed, and any important considerations or decisions made during the implementation.
</instructions>

<considerations>
- Ensure that the PR description provides enough context for reviewers who may not be familiar with the task.
- Clearly explain the reasoning behind key decisions made during implementation.
- Use markdown formatting for clarity and readability.
</considerations>

<constraints>
Your PR description should NOT:
- Include unnecessary technical jargon that might confuse the reader.
- Be overly verbose or include redundant information.
- Include detailed implementation code; focus on describing what was done and why.
</constraints>

`;
    }

    getPrompt(request: CodingTaskRequest): string {
        return `
Here is the task description:
<task_description>
${TASK_PLACEHOLDER}
</task_description>

Here is the implementation plan to follow for the task:
${PLAN_PLACEHOLDER}

Here is the code generated by the coding assistant:
<generated_code>
${GENERATED_CODE_PLACEHOLDER}
</generated_code>

<response_format_instructions>
<pr_title>title of the pr</pr_title>
<pr_body>Respond with the PR description in markdown format.</pr_body>
</response_format_instructions>

Note: **Do not repeat yourself in the PR description.**

Please go ahead and generate the PR description based on the provided information.
`;
    }

    handleResponse(response: string): PRBody {
        const title = response.match(/<pr_title>(.*?)<\/pr_title>/)?.[1] || "";
        const body = response.match(/<pr_body>([\s\S]*?)<\/pr_body>/)?.[1] || "";

        return { title, body };
    }
}
