import {
    CODEFILES_PLACEHOLDER,
    GENERATED_CODE_PLACEHOLDER,
    PLAN_PLACEHOLDER,
    TASK_PLACEHOLDER,
} from "@/constants";
import { BaseAssistant } from "./BaseAssistant";

export class WriterAssistant extends BaseAssistant<string> {
    constructor() {
        super();
    }

    getSystemPrompt(): string {
        return `
You are a senior software engineer working on a project.
Your task is to write a clear and concise pull request (PR) description in markdown format, based on the provided task description, implementation plan, existing code files, and generated code.

### Objective:
Analyze the task, the implementation plan, the existing codebase, and the newly generated code to craft a comprehensive PR description. This description should provide context, outline the changes made, and explain the reasoning behind the implementation.

Each PR description should include:

- Title: A brief and descriptive title for the PR.
- Summary: A concise overview of the changes and the purpose of the PR.
- Details: A detailed explanation of what was changed, why it was changed, and any important considerations or decisions made during the implementation.

### Considerations:
- Ensure that the PR description provides enough context for reviewers who may not be familiar with the task.
- Clearly explain the reasoning behind key decisions made during implementation.
- Highlight any potential impact on other parts of the codebase or system.
- Use markdown formatting for clarity and readability.

### Constraints:

Your PR description should NOT:

- Include unnecessary technical jargon that might confuse the reader.
- Be overly verbose or include redundant information.
- Include detailed implementation code; focus on describing what was done and why.

`;
    }

    getPrompt(params: any | null): string {
        return `
### Existing Codebase:
Here are the existing code files you will be working with:

${CODEFILES_PLACEHOLDER}

### Task Description:
Here is the task description:

${TASK_PLACEHOLDER}

### Implementation Plan:
Here is the implementation plan to follow for the task:

${PLAN_PLACEHOLDER}

### Generated Code:
Here is the code generated by the coding assistant:

${GENERATED_CODE_PLACEHOLDER}

Response Format:
Respond with the PR description in markdown format.

**Do not repeat yourself in the PR description.**
`;
    }
}
