export const EMBEDDINGS_MODEL = "text-embedding-3-large";
export const TITAN_EMBEDDINGS_MODEL = "amazon.titan-embed-text-v2:0";
export const EMBEDDINGS_DIMENSIONS = 256;
export const EMBEDDINGS_MAX_TOKENS = 8191;

export const CODEFILES_PLACEHOLDER = "[[EXISTINGCODEFILES]]";
export const TASK_PLACEHOLDER = "[[TASKDESCRIPTION]]";
export const SPECS_PLACEHOLDER = "[[SPECIFICATIONS]]";
export const PLAN_PLACEHOLDER = "[[IMPLEMENTATIONPLAN]]";
export const GENERATED_CODE_PLACEHOLDER = "[[GENERATEDCODE]]";

export const CHUNK_ANALYSES_PLACEHOLDER = "[[CHUNKANALYSES]]";
export const TECHNICAL_DESIGN_DOC_PLACEHOLDER = "[[TECHNICALDESIGNDOC]]";
export const FEATURE_PLACEHOLDER = "[[FEATUREFORJIRA]]";

export const CRITICAL_PATTERNS_PLACEHOLDER = "[[CRITICALPATTERNS]]";

export const PRD_ANALYSIS_PLACEHOLDER = "[[PRODUCTDOCUMENT]]";

// archive assistants
export const REPO_ANALYSIS_PLACEHOLDER = "[[REPOANALYSIS]]";
export const GAP_ANALYSIS_PLACEHOLDER = "[[GAPANALYSIS]]";

export const DEFAULT_MAX_OUTPUT_TOKENS = 8192;
